name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install platformio==6.1.5
      - name: Build firmware
        run: platformio run
      - name: Archive
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
